### PR TITLE
Fix custom labels draw

### PR DESCRIPTION
**Pull request by FalsinSoft**
If custom labels are set to axes, in case of two labels need to be showed only the first one is showed and the second is not showed. This change allow all the labels to be showed correctly.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi! Thanks for the PR. I have a few requests:
1. Please resolve conflicts
2. Please demonstrate the effect of your change (e.g. with screenshots)

**Comment by jkriege2** [comment]
PS: for fixing the conflicts, easiest is to rebase your branch.

**Comment by FalsinSoft** [comment]
Hi
Sorry for delay in reply but I'm really really busy lately. I just noted you released a new version of the library. I'll try to apply the patch to new source coded as soon as possible...

**Comment by FalsinSoft** [comment]
By the way. maybe it would be more faster if you apply yourself the patch? It's just few lines of code...

**Comment by jkriege2** [comment]
I can look into it ... Will let you know

**Comment by jkriege2** [comment]
OK; I can confirm the bug and see that your fix works ... I'll merge it - in your name of course - and will close this PR!

**Comment by jkriege2** [comment]
fixed the issue described here by https://github.com/jkriege2/JKQtPlotter/commit/94f80510ec01ac7c6ee3f92628be7beb158bb12e

Thanks again,
JAN

**Pull request closed without merging**
