### PR TITLE
Improve Travis: test on Linux and macOS

### PR DESCRIPTION
**Pull request by certik**
Keep the Doxygen run as before, but also test building and installing
using cmake on Linux and macOS with both gcc and clang.

### CODE REVIEW

**Comment by certik** [comment]
@jkriege2 this is now ready for review. I only changed the Travis config and added one macOS build (the default clang compiler) and two Linux builds (gcc and clang). For now we only test that it builds and can be installed.

After this is merged, I'll submit PRs to check that all shared libraries are found (#25). You can also see all the warnings with the clang compiler (both on Linux and macOS) that should be fixed (in another PR).

**Comment by certik** [comment]
@jkriege2 let me know if you have any feedback on this. The Windows failures (#27) are unrelated to this PR.

**Comment by jkriege2** [comment]
Hhmmm ... for sure interesting ... what I don't like is that Travis now builds doxygen AND the CI-tests in one go ... before I had travis for the docu and AppVeyor for the CI-builds ... but maybe it's also just getting used to mixing the two steps ;-) ... I will get back to you during the weekend or next week ...

Anyways: Many thanks for all the contributions you made so far!

**Comment by certik** [comment]
I am not sure I understand your concern: the doxygen build is a dedicated Travis build, exactly as before. All I did was add *additional* builds. Or is the concern in the way the `.travis.yml` file is structured now? I would agree with that, I use GitLab CI a lot, and there every build has a dedicated section, it's not all mixed together. Travis unfortunately does not allow that.

Another option is to use GitHub Actions for testing on all three platforms, I think the builds are separate there, not mixed all together.

I don't care what CI is being used, as long as your library is reliably tested and works on all three platforms (Linux gcc/clang, macOS clang and Windows MSVC).

**Comment by jkriege2** [comment]
Thanks ... a lot ;-)

JAN

**Comment by certik** [comment]
@jkriege2 thanks for merging! Now we just need to fix the Windows CI to pass in master.

**Pull request merged**
