### PR TITLE
Skip drawing the line for negative values in log plots

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi and thanks for the contribution ... i have two requests:
1. Please post a Screenshot of the old vs. The  fixed plots that illustrate the problem and solution
2. Why do you use a vector of uniqe_ptr instead of a simple vector of polygons?
Best, jan

**Comment by certik** [comment]
Regarding 1., here are two screenshots of the current behavior. It's the same graph moved using the "hand" tool:

old1
old2

as you can see, the graph changed it's shape simply by moving it. That is not optimal.

In this PR, the graph looks like this:

new

and it is invariant when you move it around with the "hand" tool. As it should be. Matplotlib has the same behavior as this PR.

**Comment by certik** [comment]
Regarding 2., that was fixed in ae722e8c3361290ee67c2ce74efed976fec783bb.

**Comment by jkriege2** [comment]
OK!

great addition!

Thanks,
JAN

**Pull request merged**
