### PR TITLE
Set the proper RPATH for installed libraries

### LINKED ISSUE #25: JKQT libraries do not have the proper RPATH setup on Linux
With the latest master (cbd9882a30be54559cf105efbe30f0f3bfd34025) I am now facing another problem:
```
$ ldd my_application
	linux-vdso.so.1 (0x00007ffda94ce000)
	libJKQTPlotterSharedLib_.so.2019.11 => /home/certik/miniconda3/envs/qt/lib/libJKQTPlotterSharedLib_.so.2019.11 (0x00007fcc9eb9d000)
	libQt5Widgets.so.5 => /home/certik/miniconda3/envs/qt/lib/libQt5Widgets.so.5 (0x00007fcc9e656000)
	libQt5Gui.so.5 => /home/certik/miniconda3/envs/qt/lib/libQt5Gui.so.5 (0x00007fcc9e249000)
	libQt5Core.so.5 => /home/certik/miniconda3/envs/qt/lib/libQt5Core.so.5 (0x00007fcc9ddf1000)
	libstdc++.so.6 => /home/certik/miniconda3/envs/qt/lib/libstdc++.so.6 (0x00007fcc9f357000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcc9da53000)
	libgcc_s.so.1 => /home/certik/miniconda3/envs/qt/lib/libgcc_s.so.1 (0x00007fcc9f325000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcc9d662000)
	libQt5Svg.so.5 => not found
	libJKQTMathTextSharedLib_.so.2019.11 => not found
	libJKQTCommonSharedLib_.so.2019.11 => not found
	libQt5PrintSupport.so.5 => not found
```
As you can see, some Qt5 libraries and `libJKQTPlotterSharedLib` have the proper RPATH, but the `libQt5Svg`, `libQt5PrintSupport`, `libJKQTMathTextSharedLib` and `libJKQTCommonSharedLib` libraries do not.

Here is my `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.15.5 FATAL_ERROR)

project(my_application LANGUAGES CXX)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

# Qt
find_package(Qt5 COMPONENTS Core Widgets PrintSupport Svg Xml REQUIRED)

# JKQtPlotter
find_package(JKQTCommonSharedLib REQUIRED)
find_package(JKQTMathTextSharedLib REQUIRED)
find_package(JKQTPlotterSharedLib REQUIRED)

add_executable(my_application main.cpp mainform.cpp mainform.ui)
target_link_libraries(my_application JKQTPlotterSharedLib)
```

### PR DESCRIPTION
**Pull request by certik**
Fixes #25. Now everything works on Linux out of the box.

### CODE REVIEW

**Comment by certik** [comment]
The fix was taken from page 100 at https://crascit.com/wp-content/uploads/2019/09/Deep-CMake-For-Library-Authors-Craig-Scott-CppCon-2019.pdf.

**Comment by jkriege2** [comment]
Thanks, I will merge this. But please move your lines to this file: https://github.com/jkriege2/JKQtPlotter/blob/master/cmake/jkqtplotter_common_compilersettings.cmake ... I'm trying to keep such things in one place

**Comment by jkriege2** [comment]
PS: Thanks for the talk PDF ... that is quite interesting and I will have another look at it and maybe include some more stuff from there!

thanks,
JAN

**Comment by certik** [comment]
@jkriege2 Thanks for the review. I moved it as you suggested. I tested it and it still works for me.

**Comment by jkriege2** [comment]
Thanks
JAN

**Comment by certik** [comment]
Thank you @jkriege2 for merging.

**Pull request merged**
