### PR TITLE
Support for iOS devices & ability to build without QtPrinterSupport

### PR DESCRIPTION
**Pull request by sufuk**
[Related issue](https://github.com/jkriege2/JKQtPlotter/issues/81)
Project can be built for iOS by disabling using new CMake option "QT_PRINT_SUPPORT" and using QtiOSCMake toolchain file which can be found in repository. All of the "print" related codes are enclosed with;
```
#ifndef QT_NO_PRINTER
 ...
#endif
```
Build Options:
```
-G Xcode
-DCMAKE_PREFIX_PATH=/Users/semihufuk/Qt/5.15.2/ios
-DDEPLOYMENT_TARGET=12.0
-DCMAKE_TOOLCHAIN_FILE=$CMakeProjectDir$/QtIosCmake/ios.toolchain.cmake
-DPLATFORM=OS64COMBINED
-DENABLE_BITCODE=FALSE
-DQT_PRINT_SUPPORT=OFF
-DJKQtPlotter_BUILD_EXAMPLES=OFF
-DCMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM=!!!!!!!!!!!!!!
-DJKQtPlotter_BUILD_STATIC_LIBS=ON
-DJKQtPlotter_BUILD_SHARED_LIBS=OFF
-DCMAKE_INSTALL_PREFIX=/Users/semihufuk/JKQTPLOTTER/os64combined
```
Build Environment
- Builded with Qt 5.15.2 iOS Static Library,
- MacOS monterey 12.4
- Apple MacBook Pro M1

Notes:
- DPLATFORM=OS64COMBINED builds project for both arm64 and iOS simulator, I built my application for both of these without a problem but I only tested in Simulator
- Reason I build as a static library Qt doesn't provide pre-built shared library for iOS.
- Examples should be OFF otherwise build will fail, their cmake(s) should be edited for compability

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work ... thanks so far ...

I also looked a bit into this: To me it seems that the macro QT_NO_PRINTER will already be defined by QT if QPrinter-support is not availble (they use it throughout Qt code e.g. in QTextDocument ... and many other libraries assume it beeing availble too). Therefore we don't need to define our own option in the CMakeLists.txt-files, I think. Can you confirm my supicion for your Qt-for-iOS?

Since this PR now covers two topics, I would suggest the following: I will do the #ifndef-stuff myself in the  master branch and I will make PrintSupport an optional component (CMake allows that, see e.g. https://github.com/qt/qtcharts/blob/dev/CMakeLists.txt line 20 )

Then you could check whether it works with your additions for iOS and we can deal with all required changes.
This PR can then be reduced to the single topic of iOS-support only. (I will still mention you in the release notes for contributions to optional QPrintSupport of course!!!).

Hope that's fine for you!

Best,
JAN

PS: I will start on the mentioned work above right now!

**Comment by sufuk** [comment]
> Hi!
> 
> nice work ... thanks so far ...
> 
> I also looked a bit into this: To me it seems that the macro QT_NO_PRINTER will already be defined by QT if QPrinter-support is not availble (they use it throughout Qt code e.g. in QTextDocument ... and many other libraries assume it beeing availble too). Therefore we don't need to define our own option in the CMakeLists.txt-files, I think. Can you confirm my supicion for your Qt-for-iOS?
> 
> Since this PR now covers two topics, I would suggest the following: I will do the #ifndef-stuff myself in the master branch and I will make PrintSupport an optional component (CMake allows that, see e.g. https://github.com/qt/qtcharts/blob/dev/CMakeLists.txt line 20 )
> 
> Then you could check whether it works with your additions for iOS and we can deal with all required changes. This PR can then be reduced to the single topic of iOS-support only. (I will still mention you in the release notes for contributions to optional QPrintSupport of course!!!).
> 
> Hope that's fine for you!
> 
> Best, JAN
> 
> PS: I will start on the mentioned work above right now!

Hello JAN,

Of course it fine for me but,
I tested again without add_compile_definitions(QT_NO_PRINTER) but QT_NO_PRINTER is not defined, I also see people saying QT_NO_PRINTER is defined automatically online but in this case it is not maybe it is related with Qt version I am using (5.15.2) ıdk, also I think it is better to add a cmake option some users may want to disable QPrinter library even if their platform supports for me example I build your library for android without a QPrinterSupport because I want to use "equally builded" library in both iOS and Android. And I for iOS support QPrinter modifications is enough, I only added ios toolchain file to repository and it may not be the "best practice" to use it.

So my suggestion is  keep cmake option for disabling QPrintSupport and maybe editing examples for iOS support.
İt is very kind of you to mentioning me in release notes thank you.

**Comment by jkriege2** [comment]
Hmmm ... strange ... I was thinking to add an option to deactivate print-support for testung purposes anyways

**Comment by sufuk** [comment]
> Hmmm ... strange ... I was thinking to add an option to deactivate print-support for testung purposes anyways

Is there anything else about this I can help?

**Comment by jkriege2** [comment]
Please rebate and modify to only add iOS compile capabilities.

Thanks!

**Comment by jkriege2** [comment]
Is anything from this PR still necessary for the iOS build? If not: please close it, if yes: please rebase so I can merge

**Pull request closed without merging**
