### PR TITLE
Add-qt5.12.12-compatibility

### PR DESCRIPTION
**Pull request by Social-Mean**
I'm not sure if the modification in `examples\libexampletools\jkqtpexampleapplication.h` is  correctly, but now it doesn't report errors.

### CODE REVIEW

**Review by Social-Mean — COMMENTED** [review]
This PR fix for issue  #124

**Review by Social-Mean — COMMENTED** [review]
Here is another problem. When I run `.exe`s in `build/output` directory, no window appears. Maybe there is something still wrong.

**Review by Social-Mean — COMMENTED** [review]
@jkriege2

**Comment by jkriege2** [comment]
Hi!

thanks for your PR ... I have only one comment:
Could you initialze the data members in the added default constructor in [examples/libexampletools/jkqtpexampleapplication.h](https://github.com/jkriege2/JKQtPlotter/pull/127/files#diff-bdd0d9c6cdf4e33ed0fed43f12bd466f0cc503a148cd3cc1c52b96217151ce15):

`type(PlotterType), f(), plotf(), p(nullptr)
`
or simply change the following constructor by definig default arguments:

```
 inline Data(JKQTPlotter* p_=nullptr):
      type(PlotterType), f(), plotf(), p(p_)
  {}


```

**Review by Social-Mean — COMMENTED** [review]
> Hi!
> 
> thanks for your PR ... I have only one comment:
> Could you initialze the data members in the added default constructor in [examples/libexampletools/jkqtpexampleapplication.h](https://github.com/jkriege2/JKQtPlotter/pull/127/files#diff-bdd0d9c6cdf4e33ed0fed43f12bd466f0cc503a148cd3cc1c52b96217151ce15):
> 
> `type(PlotterType), f(), plotf(), p(nullptr)
> `
> or simply change the following constructor by definig default arguments:
> 
> ```
>  inline Data(JKQTPlotter* p_=nullptr):
>       type(PlotterType), f(), plotf(), p(p_)
>   {}
> 
> 
> ``` 

Hi @jkriege2, I have added a default argument in Data's constructor. But still no window appear after I run `.exe`s in `build/output` directory.

**Comment by jkriege2** [comment]
OK, I will merge this for now and try how it works for me for Qt5.12.12 ... 

BTW: Which exammple did you try to run? Anything specific,or just any?

**Comment by Social-Mean** [comment]
Any example.

**Comment by jkriege2** [comment]
strange ... I tried it on my computer with a freshly downloaded Qt 5.12.12 64bit and MinGW 7.3.0 in DEBUG and RELEASE ... and it works for my:


```
[cmake] -- =============================================================================
[cmake] -- == JKQTPlotterLib Build Information                                        ==
[cmake] -- =============================================================================
[cmake] -- Version:               5.0.0
[cmake] -- CMake Generator:       Ninja
[cmake] --    is multi-config:    NO
[cmake] -- Build type:            Release
[cmake] -- Build types:           
[cmake] -- Build shared lib:      ON
[cmake] -- Using CMake:           3.27.7
[cmake] -- Using CMake Generator: Ninja
[cmake] -- Using compiler:        GNU 7.3.0, platform: MinGW
[cmake] -- C++ Standard:          C++ 11, required: TRUE
[cmake] -- LIB-Architecture:      CXX:  / BASE: 
[cmake] -- bit depth:             64 bit
[cmake] -- System Name:           Windows
[cmake] -- Processor Name:        AMD64
[cmake] -- Using Qt:              5.12.12
[cmake] --                        [at C:/development/Qt/5.12.12/mingw73_64/lib/cmake/Qt5]
[cmake] -- XITS fonts:            LINKED IN
[cmake] -- FIRA fonts:            LINKED IN
[cmake] -- Print support:         ON
[cmake] -- Timing Info output:    ON
[cmake] -- Precompiled Header:    ON
[cmake] -- build JKQTMath:        ON
[cmake] -- build JKQTMathText:    ON
[cmake] -- build JKQTFastPlotter: ON
[cmake] -- build JKQTPlotter:     ON
[cmake] -- Installing to:         C:/Program Files (x86)/JKQTPlotter
[cmake] -- =============================================================================
[cmake] -- 

```

Can you compile in debug-mode and debug to check where the program hangs?

**Pull request merged**
