### PR TITLE
Support compiling under Windows using MSVC2015

### PR DESCRIPTION
**Pull request by srazi**
Hi, this is a great project. Thank you for sharing it.
I want to use it under Windows using MSVC. Currently, I have fixed some compile issues. But there are some other issues that I hope you can help me about fixing them.

- [x] Error: C1061: compiler limit: blocks nested too deeply: [jkqtmathtext.cpp#L2175](https://github.com/jkriege2/JKQtPlotter/blob/master/lib/jkqtmathtext/jkqtmathtext.cpp#L2175)

- [x] Error: C2668: `fpclassify`: ambiguous call to overloaded function: `fpclassify` has 3 overloads: `fpclassify(float)`, `fpclassify(double)` and `fpclassify(long double)`.
**Places of  ambiguous calls:**

- [x] `JKQTPimagePlot_getImageMin<uint8_t>()` ==> `std::isnan(v) || std::isinf(v)`

- [x] `JKQTPimagePlot_array2RGBimage<uint8_t>()` ==> `std::isfinite(v)`

- [x] `JKQTPimagePlot_array2image<uint8_t>()` ==> `std::isnan(v) || std::isinf(v)`

Would you please help me to fix them?

P.S.: `dirent.h` is not available here and removing it didn't lead to compile issue, yet.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

about the `std::isfinite(), std::ifinf(), std::isnan()` ... hmmm you could maybe use something like `std::isfinite(static_cast<long double>(v))`, assuming long double is the datatype which can best represent all other datatypes (at least in terms of the inf/nan/finite-determination, which is not really needed for ints anyways and should always result in the OK-output)

Does that help?
JAN

PS: Nice that you find this useful!

**Comment by jkriege2** [comment]
PS: I will happily merge this, obce you're done !

**Comment by jkriege2** [comment]
Hi!

nice work ... I also just now submitted some code that I prepared weeks ago that solves some of your problems, also I fixed the warning you noted above (please pull from master, to resolve conflicts).

Best,
JAN

**Comment by jkriege2** [comment]
PS: For merging, could you not select the `std::isfinite(static_cast<long double>(v))`-solution by #ifdef, but rather make it the default solution? It should work generally for any compiler

**Comment by srazi** [comment]
Hi,
Commits were updated with necessary changes. (removed my if-else fix and removed `#ifdef`s).

**Comment by srazi** [comment]
If you prefer one commit I can mix all commits in one commit.

**Comment by jkriege2** [comment]
I renamed some of the tests ... does this fix your problem?

**Comment by srazi** [comment]
Rebased on current master and ready to merge.

**Comment by jkriege2** [comment]
nice work!

Thanks for your contribution.

Best,
JAN

**Comment by srazi** [comment]
You’re Welcome!

**Pull request merged**
