### PR TITLE
Compile Error on Windows fixed

### PR DESCRIPTION
**Pull request by bilaljo**
See Build Fails on Windows because of std::min #130

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the PR ... may II ask you to change the location of this flag?
If you put it here, it might interfere with projects that compile this library using FetchContent, as this uses the same CMakeLists.txt.

The better location is the function jkqtplotter_setDefaultLibOptions() in https://github.com/jkriege2/JKQtPlotter/blob/master/cmake/jkqtplotter_macros.cmake

There please use target_compile_definitions(${TARGETNAME} PRIVATE NOMINMAX)

This way, the flag is only set WHILE compiling JKQTPlotter and never exposed to other products

**Comment by jkriege2** [comment]
Hi @bilaljo !

I looked into this further ... and to me the above definition should alread be part of all libraries, have a look at this code-line:

https://github.com/jkriege2/JKQtPlotter/blob/aa4ac4c58a099594e88e3c63110dff69136d54b8/cmake/jkqtplotter_macros.cmake#L38C1-L38C64

The given macro is called for all libraries and even exports the MINMAX in the target (declared as public) ...

Could ou elaborate more on the conditions under which ou found the compile errors? 

Best,
JAN

**Comment by bilaljo** [comment]
Hi Jan,

I am sorry for the delay.

Oh yes, you are right!

I did it actually without CMake, I tried to rebuild with Meson to integrate directly into my project, that explains then why it didn't work for me (cause the Macro was defined in CMake only).

**Comment by jkriege2** [comment]
OK, then this can be closed?

**Comment by bilaljo** [comment]
Yes, thanks a lot.

**Pull request closed without merging**
